"""Agregar tabla incidencias

Revision ID: 579d42dd6bd4
Revises: 
Create Date: 2025-12-02 15:14:54.707902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579d42dd6bd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('fecha_incidencia', sa.DateTime(), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('tiempo_resolucion', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('severidad', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('causa_raiz', sa.Text(), nullable=True),
    sa.Column('solucion_aplicada', sa.Text(), nullable=True),
    sa.Column('usuarios_afectados', sa.Integer(), nullable=True),
    sa.Column('servicios_afectados', sa.String(length=200), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.Column('resuelto_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['resuelto_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fallas_criticas_permitidas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fallas_menores_permitidas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('disponibilidad_esperada', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tiempo_max_inactividad', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mantenimiento_preventivo', sa.String(length=50), nullable=True))
        batch_op.drop_column('certificacion_req')
        batch_op.drop_column('norma_aplicable')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('norma_aplicable', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('certificacion_req', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('mantenimiento_preventivo')
        batch_op.drop_column('tiempo_max_inactividad')
        batch_op.drop_column('disponibilidad_esperada')
        batch_op.drop_column('fallas_menores_permitidas')
        batch_op.drop_column('fallas_criticas_permitidas')

    op.drop_table('incidencia')
    # ### end Alembic commands ###
